sudo: required
language: generic

services: -docker

before_install:
  - docker build -t thenickben/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true thenickben/react-test npm test -- --coverage

after_success:
  - docker build -t thenickben/multi-client ./client
  - docker build -t thenickben/multi-nginx ./nginx
  - docker build -t thenickben/multi-server ./server
  - docker build -t thenickben/multi-worker ./worker
  # log into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push to docker hub
  - docker push thenickben/multi-client
  - docker push thenickben/multi-nginx
  - docker push thenickben/multi-server
  - docker push thenickben/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "Twistedfibo"
  env: "Twistedfibo-env"
  bucket_name: "elasticbeanstalk-eu-west-2-695166529321"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
